// regras de cada mercado (o que cada cotação precisa para ganhar), com os textos de
// screens/rules do sistema antigo (spec 006, FR-023a). Textos fixos: não mudam com a configuração.
// rotulo nulo = texto sem rótulo ('E assim por diante.'); espaco_antes = linha em branco antes,
// como os <br /> do antigo

export const regras_mercados = [
    {
        titulo: 'PRINCIPAL',
        itens: [
            { rotulo: 'CASA', texto: 'Time mandante precisa vencer.' },
            { rotulo: 'EMPATE', texto: 'Ambos times precisam fazer total de gols iguais nos 90 minutos.' },
            { rotulo: 'FORA', texto: 'Time visitante precisa vencer.' },
        ],
    },
    {
        titulo: 'AMBAS AS EQUIPES MARCAM',
        itens: [
            { rotulo: 'AMBAS MARCAM', texto: 'Time mandante e visitante precisa marcar gol.' },
            { rotulo: 'AMBAS NÃO MARCAM', texto: 'Nenhuma ou apenas uma das equipes marcar gol.' },
        ],
    },
    {
        titulo: 'DUPLA CHANCE',
        itens: [
            { rotulo: 'CASA OU EMPATE', texto: 'Time mandante precisa vencer ou empatar.' },
            { rotulo: 'CASA OU FORA', texto: 'Time mandante ou time visitante precisa vencer.' },
            { rotulo: 'FORA OU EMPATE', texto: 'Time visitante precisa vencer ou empatar.' },
        ],
    },
    {
        titulo: 'HANDICAP ASIÁTICO',
        itens: [
            { rotulo: 'CASA -4.5', texto: 'Time mandante precisa fazer 5 gols ou mais de diferença em relação ao visitante.' },
            { rotulo: 'CASA -3.5', texto: 'Time mandante precisa fazer 4 gols ou mais de diferença em relação ao visitante.' },
            { rotulo: 'CASA -2.5', texto: 'Time mandante precisa fazer 3 gols ou mais de diferença em relação ao visitante.' },
            { rotulo: 'CASA -1.5', texto: 'Time mandante precisa fazer 2 gols ou mais de diferença em relação ao visitante.' },
            { rotulo: 'CASA -0.5', texto: 'Time mandante precisa fazer 1 gol ou mais de diferença em relação ao visitante.' },
            { rotulo: 'CASA +4.5', texto: 'Time visitante fizer menos de 5 gols de diferença em relação ao mandante você vence.', espaco_antes: true },
            { rotulo: 'CASA +3.5', texto: 'Time visitante fizer menos de 4 gols de diferença em relação ao mandante você vence.' },
            { rotulo: 'CASA +2.5', texto: 'Time visitante fizer menos de 3 gols de diferença em relação ao mandante você vence.' },
            { rotulo: 'CASA +1.5', texto: 'Time visitante fizer menos de 2 gols de diferença em relação ao mandante você vence.' },
            { rotulo: 'CASA +0.5', texto: 'Time mandante vencer ou empatar a partida você vence.' },
            { rotulo: 'FORA -4.5', texto: 'Time visitante precisa fazer 5 gols ou mais de diferença em relação ao mandante.', espaco_antes: true },
            { rotulo: 'FORA -3.5', texto: 'Time visitante precisa fazer 4 gols ou mais de diferença em relação ao mandante.' },
            { rotulo: 'FORA -2.5', texto: 'Time visitante precisa fazer 3 gols ou mais de diferença em relação ao mandante.' },
            { rotulo: 'FORA -1.5', texto: 'Time visitante precisa fazer 2 gols ou mais de diferença em relação ao mandante.' },
            { rotulo: 'FORA -0.5', texto: 'Time visitante precisa fazer 1 gol ou mais de diferença em relação ao mandante.' },
            { rotulo: 'FORA +4.5', texto: 'Time mandante fizer menos de 5 gols de diferença em relação ao visitante você vence.', espaco_antes: true },
            { rotulo: 'FORA +3.5', texto: 'Time mandante fizer menos de 4 gols de diferença em relação ao visitante você vence.' },
            { rotulo: 'FORA +2.5', texto: 'Time mandante fizer menos de 3 gols de diferença em relação ao visitante você vence.' },
            { rotulo: 'FORA +1.5', texto: 'Time mandante fizer menos de 2 gols de diferença em relação ao visitante você vence.' },
            { rotulo: 'FORA +0.5', texto: 'Time mandante fizer menos de 1 gols de diferença em relação ao visitante você vence.' },
        ],
    },
    {
        titulo: 'INTERVALO | FINAL DE JOGO',
        itens: [
            { rotulo: 'CASA - CASA', texto: 'Time mandante precisa vencer 1° tempo e resultado final.' },
            { rotulo: 'CASA - EMPATE', texto: 'Time mandante precisa vencer 1° tempo e resultado final ser empate.' },
            { rotulo: 'CASA - FORA', texto: 'Time mandante precisa vencer no 1º tempo e perder no resultado final.' },
            { rotulo: 'EMPATE - CASA', texto: 'Times precisam empatar no 1º tempo e mandante vencer no resultado final.', espaco_antes: true },
            { rotulo: 'EMPATE - EMPATE', texto: 'Times precisam empatar no 1º tempo e resultado final ser empate.' },
            { rotulo: 'EMPATE - FORA', texto: 'Times precisam empatar no 1º tempo e visitante vencer no resultado final.' },
            { rotulo: 'FORA - CASA', texto: 'Time visitante precisa vencer no 1º tempo e perder no resultado final.', espaco_antes: true },
            { rotulo: 'FORA - EMPATE', texto: 'Time visitante precisa vencer no 1º tempo e empatar no resultado final.' },
            { rotulo: 'FORA - FORA', texto: 'Time visitante precisa vencer 1° tempo e resultado final.' },
        ],
    },
    {
        titulo: 'RESULTADO EXATO',
        itens: [
            { rotulo: 'PLACAR EXATO ( 0 X 0 )', texto: 'Resultado final da partida precisa ser 0 x 0.' },
            { rotulo: 'PLACAR EXATO ( 0 X 1 )', texto: 'Resultado final da partida precisa ser 0 x 1.' },
            { rotulo: 'PLACAR EXATO ( 0 X 2 )', texto: 'Resultado final da partida precisa ser 0 x 2.' },
            { rotulo: 'PLACAR EXATO ( 0 X 3 )', texto: 'Resultado final da partida precisa ser 0 x 3.' },
            { rotulo: 'PLACAR EXATO ( 0 X 4 )', texto: 'Resultado final da partida precisa ser 0 x 4.' },
            { rotulo: 'PLACAR EXATO ( 0 X 5 )', texto: 'Resultado final da partida precisa ser 0 x 5.' },
            { rotulo: null, texto: 'E assim por diante.' },
        ],
    },
    {
        titulo: 'TOTAL DE GOLS',
        itens: [
            { rotulo: '1 GOL NA PARTIDA', texto: 'O total de gols na partida deve ser igual a 1.' },
            { rotulo: '2 GOLS NA PARTIDA', texto: 'O total de gols na partida deve ser igual a 2.' },
            { rotulo: '3 GOLS NA PARTIDA', texto: 'O total de gols na partida deve ser igual a 3.' },
            { rotulo: '4 GOLS NA PARTIDA', texto: 'O total de gols na partida deve ser igual a 4.' },
            { rotulo: '5 GOLS NA PARTIDA', texto: 'O total de gols na partida deve ser igual a 5.' },
            { rotulo: '6 GOLS NA PARTIDA', texto: 'O total de gols na partida deve ser igual a 6.' },
            { rotulo: 'MAIS DE 7 GOLS NA PARTIDA', texto: 'O total de gols na partida deve ser igual ou maior que 7.' },
        ],
    },
    {
        titulo: 'GOLS MAIS/MENOS',
        itens: [
            { rotulo: '+1.5 GOLS', texto: 'O total de gols na partida deve ser igual ou maior que 2.' },
            { rotulo: '+2.5 GOLS', texto: 'O total de gols na partida deve ser igual ou maior que 3.' },
            { rotulo: '+3.5 GOLS', texto: 'O total de gols na partida deve ser igual ou maior que 4.' },
            { rotulo: '+4.5 GOLS', texto: 'O total de gols na partida deve ser igual ou maior que 5.' },
            { rotulo: '+5.5 GOLS', texto: 'O total de gols na partida deve ser igual ou maior que 6.' },
            { rotulo: '+6.5 GOLS', texto: 'O total de gols na partida deve ser igual ou maior que 7.' },
            { rotulo: '-0.5 GOLS', texto: 'O total de gols na partida deve ser igual a 0.', espaco_antes: true },
            { rotulo: '-1.5 GOLS', texto: 'O total de gols na partida deve ser igual ou menor que 1.' },
            { rotulo: '-2.5 GOLS', texto: 'O total de gols na partida deve ser igual ou menor que 2.' },
            { rotulo: '-3.5 GOLS', texto: 'O total de gols na partida deve ser igual ou menor que 3.' },
        ],
    },
    {
        titulo: 'GOLS PAR/ÍMPAR',
        itens: [
            { rotulo: 'IMPAR', texto: 'O total de gols na partida deve ser impar.' },
            { rotulo: 'PAR', texto: 'O total de gols na partida deve ser par.' },
        ],
    },
    {
        titulo: 'VENCEDOR E AMBAS EQUIPES',
        itens: [
            { rotulo: 'CASA GANHA, AMBAS MARCAM', texto: 'O time de mandante precisa vencer a partida e o time de visitante fazer gol.' },
            { rotulo: 'CASA GANHA, AMBAS NÃO MARCAM', texto: 'O time de mandante precisa vencer a partida e o time de visitante não fazer gol.' },
            { rotulo: 'EMPATE, AMBAS MARCAM', texto: 'A partida precisa sair empate e sair gols de ambos os lados.', espaco_antes: true },
            { rotulo: 'EMPATE, AMBAS NÃO MARCAM', texto: 'A partida precisa sair 0 x 0.' },
            { rotulo: 'FORA GANHA, AMBAS MARCAM', texto: 'O time de visitante precisa vencer a partida e o time mandante fazer gol.', espaco_antes: true },
            { rotulo: 'FORA GANHA, AMBAS NÃO MARCAM', texto: 'O time de visitante precisa vencer a partida e o time mandante não fazer gol.' },
        ],
    },
    {
        titulo: 'RESULTADOS E TOTAL DE GOLS',
        itens: [
            { rotulo: 'CASA, +2.5 GOLS', texto: 'O time mandante precisa vencer e o total de gols na partida ser igual ou maior que 3.' },
            { rotulo: 'CASA, -2.5 GOLS', texto: 'O time mandante precisa vencer e o total de gols na partida ser igual ou menor que 2.' },
            { rotulo: 'EMPATE, +2.5 GOLS', texto: 'A partida precisa sair empate e o total de gols ser igual ou maior que 3.', espaco_antes: true },
            { rotulo: 'EMPATE, -2.5 GOLS', texto: 'A partida precisa sair empate e o total de gols na partida ser igual ou menor que 2.' },
            { rotulo: 'FORA, +2.5 GOLS', texto: 'O time visitante precisa vencer e o total de gols na partida ser igual ou maior que 3.', espaco_antes: true },
            { rotulo: 'FORA, -2.5 GOLS', texto: 'O time visitante precisa vencer e o total de gols na partida ser igual ou menor que 2.' },
        ],
    },
    {
        titulo: 'EMPATE ANULA APOSTA',
        itens: [
            { rotulo: 'CASA', texto: 'O time de mandante precisa vencer, caso empate o palpite é retirado do seu bilhete, recalculado o valor da premiação e continuará valendo.' },
            { rotulo: 'FORA', texto: 'O time de visitante precisa vencer, caso empate o palpite é retirado do seu bilhete, recalculado o valor da premiação e continuará valendo.' },
        ],
    },
    {
        titulo: 'ESCANTEIOS ACIMA/ABAIXO',
        itens: [
            { rotulo: 'ACIMA DE 2', texto: 'Total de escanteios na partida precisa ser maior que 2.' },
            { rotulo: 'ACIMA DE 3', texto: 'Total de escanteios na partida precisa ser maior que 3.' },
            { rotulo: 'ACIMA DE 4', texto: 'Total de escanteios na partida precisa ser maior que 4.' },
            { rotulo: 'ACIMA DE 5', texto: 'Total de escanteios na partida precisa ser maior que 5.' },
            { rotulo: 'ACIMA DE 6', texto: 'Total de escanteios na partida precisa ser maior que 6.' },
            { rotulo: 'ACIMA DE 7', texto: 'Total de escanteios na partida precisa ser maior que 7.' },
            { rotulo: 'ACIMA DE 8', texto: 'Total de escanteios na partida precisa ser maior que 8.' },
            { rotulo: null, texto: 'E assim por diante.' },
            { rotulo: 'ABAIXO DE 2', texto: 'Total de escanteios na partida precisa ser menor que 2.' },
            { rotulo: 'ABAIXO DE 3', texto: 'Total de escanteios na partida precisa ser menor que 3.' },
            { rotulo: 'ABAIXO DE 4', texto: 'Total de escanteios na partida precisa ser menor que 4.' },
            { rotulo: 'ABAIXO DE 5', texto: 'Total de escanteios na partida precisa ser menor que 5.' },
            { rotulo: 'ABAIXO DE 6', texto: 'Total de escanteios na partida precisa ser menor que 6.' },
            { rotulo: 'ABAIXO DE 7', texto: 'Total de escanteios na partida precisa ser menor que 7.' },
            { rotulo: 'ABAIXO DE 8', texto: 'Total de escanteios na partida precisa ser menor que 8.' },
            { rotulo: null, texto: 'E assim por diante.' },
        ],
    },
    {
        titulo: 'ESCANTEIOS EXATOS',
        itens: [
            { rotulo: 'EXATOS 2', texto: 'Precisa ter 2 escanteios exatos na partida.' },
            { rotulo: 'EXATOS 3', texto: 'Precisa ter 3 escanteios exatos na partida.' },
            { rotulo: 'EXATOS 4', texto: 'Precisa ter 4 escanteios exatos na partida.' },
            { rotulo: 'EXATOS 5', texto: 'Precisa ter 5 escanteios exatos na partida.' },
            { rotulo: 'EXATOS 6', texto: 'Precisa ter 6 escanteios exatos na partida.' },
            { rotulo: 'EXATOS 7', texto: 'Precisa ter 7 escanteios exatos na partida.' },
            { rotulo: 'EXATOS 8', texto: 'Precisa ter 8 escanteios exatos na partida.' },
            { rotulo: null, texto: 'E assim por diante.' },
        ],
    },
    {
        titulo: 'TOTAL DE ESCANTEIOS',
        itens: [
            { rotulo: '12 a 14', texto: 'Precisa ter entre 12 e 14 escanteios na partida.' },
            { rotulo: '9 a 11', texto: 'Precisa ter entre 9 e 11 escanteios na partida.' },
            { rotulo: '6 a 8', texto: 'Precisa ter entre 6 e 8 escanteios na partida.' },
            { rotulo: 'Mais de 14', texto: 'Precisa ter mais de 14 escanteios na partida.' },
            { rotulo: 'Menos de 6', texto: 'Precisa ter menos de 6 escanteios na partida.' },
        ],
    },
    {
        titulo: 'TIME IMPAR/PAR',
        itens: [
            { rotulo: 'CASA PAR', texto: 'Total de gols apenas do mandante precisa ser par.' },
            { rotulo: 'CASA IMPAR', texto: 'Total de gols apenas do mandante precisa ser impar.' },
            { rotulo: 'FORA PAR', texto: 'Total de gols apenas do visitante precisa ser par.' },
            { rotulo: 'FORA IMPAR', texto: 'Total de gols apenas do visitante precisa ser impar.' },
        ],
    },
    {
        titulo: 'AMBAS MARCAM, 1º TEMPO / 2º TEMPO',
        itens: [
            { rotulo: 'SIM/SIM', texto: 'Ambas as equipes marcam gols no 1º e 2º tempo.' },
            { rotulo: 'SIM/NÃO', texto: 'Ambas equipes marcam gols no 1º tempo e no 2º ambas não marcam.' },
            { rotulo: 'NÃO/SIM', texto: 'Ambas equipes não marcam gol no 1º tempo e no 2º ambas marcam.' },
            { rotulo: 'NÃO/NÃO', texto: 'Ambas as equipes não marcam gols no 1º e 2º tempo.' },
        ],
    },
    {
        titulo: 'TEMPO COM MAIS GOLS',
        itens: [
            { rotulo: '1º TEMPO', texto: 'O 1º tempo precisa sair mais gols que o 2º tempo.' },
            { rotulo: '2º TEMPO', texto: 'O 2º tempo precisa sair mais gols que o 1º tempo.' },
            { rotulo: 'EMPATE', texto: 'O total de gols do 1º tempo precisa ser igual ao do 2º tempo.' },
        ],
    },
    {
        titulo: 'TIME E TEMPO COM MAIS GOLS',
        itens: [
            { rotulo: 'CASA 1º TEMPO', texto: 'Time da mandante precisa ter mais gols no 1º tempo que no segundo.' },
            { rotulo: 'CASA 2º TEMPO', texto: 'Time da mandante precisa ter mais gols no 2º tempo que no primeiro.' },
            { rotulo: 'CASA EMPATE', texto: 'Primeiro tempo do mandante precisa ter o mesmo número de gols que o segundo.' },
            { rotulo: 'FORA 1º TEMPO', texto: 'Time visitante precisa ter mais gols no 1º tempo que no segundo.' },
            { rotulo: 'FORA 2º TEMPO', texto: 'Time da visitante precisa ter mais gols no 2º tempo que no primeiro.' },
            { rotulo: 'FORA EMPATE', texto: 'Primeiro tempo do visitante precisa ter o mesmo número de gols que o segundo.' },
        ],
    },
    {
        titulo: 'TIME SEM SOFRER GOL',
        itens: [
            { rotulo: 'CASA', texto: 'Casa precisa não levar gols.' },
            { rotulo: 'FORA', texto: 'Fora precisa não levar gols.' },
        ],
    },
    {
        titulo: 'TIME SOFRE GOL',
        itens: [
            { rotulo: 'CASA', texto: 'Casa precisa levar gols.' },
            { rotulo: 'FORA', texto: 'Fora precisa levar gols.' },
        ],
    },
    {
        titulo: 'MARGEM DE VITÓRIA',
        itens: [
            { rotulo: 'CASA | 1', texto: 'Equipe mandante ganhar de 1 gol de diferença.' },
            { rotulo: 'CASA | 2', texto: 'Equipe mandante ganhar de 2 gols de diferença.' },
            { rotulo: 'CASA | 3', texto: 'Equipe mandante ganhar de 3 gols de diferença.' },
            { rotulo: 'CASA | 4+', texto: 'Equipe mandante ganhar de 4 gols ou mais de diferença.' },
            { rotulo: 'VISITANTE | 1', texto: 'Equipe visitante ganhar de 1 gol de diferença.', espaco_antes: true },
            { rotulo: 'VISITANTE | 2', texto: 'Equipe visitante ganhar de 2 gols de diferença.' },
            { rotulo: 'VISITANTE | 3', texto: 'Equipe visitante ganhar de 3 gols de diferença.' },
            { rotulo: 'VISITANTE | 4+', texto: 'Equipe visitante ganhar de 4 gols ou mais de diferença.' },
            { rotulo: 'EMPATE COM GOLS', texto: 'Equipes precisam empatar com gols.', espaco_antes: true },
            { rotulo: 'SEM GOLS', texto: 'Equipe precisam empatar sem gols.' },
        ],
    },
    {
        titulo: 'TIME - TOTAL DE GOLS',
        itens: [
            { rotulo: 'CASA +0.5', texto: 'Time mandante precisa fazer 1 gol ou mais.' },
            { rotulo: 'CASA +1.5', texto: 'Time mandante precisa fazer 2 gols ou mais.' },
            { rotulo: 'CASA +2.5', texto: 'Time mandante precisa fazer 3 gols ou mais.' },
            { rotulo: 'CASA +3.5', texto: 'Time mandante precisa fazer 4 gols ou mais.' },
            { rotulo: 'CASA +4.5', texto: 'Time mandante precisa fazer 5 gols ou mais.' },
            { rotulo: 'CASA +5.5', texto: 'Time mandante precisa fazer 6 gols ou mais.' },
            { rotulo: 'CASA +6.5', texto: 'Time mandante precisa fazer 7 gols ou mais.' },
            { rotulo: 'CASA +7.5', texto: 'Time mandante precisa fazer 8 gols ou mais.' },
            { rotulo: 'CASA +8.5', texto: 'Time mandante precisa fazer 9 gols ou mais.' },
            { rotulo: 'CASA +9.5', texto: 'Time mandante precisa fazer 10 gols ou mais.' },
            { rotulo: 'CASA -0.5', texto: 'Time mandante não marca gol.', espaco_antes: true },
            { rotulo: 'CASA -1.5', texto: 'Time mandante precisa fazer 1 gol.' },
            { rotulo: 'CASA -2.5', texto: 'Time mandante precisa fazer 2 gols ou menos.' },
            { rotulo: 'CASA -3.5', texto: 'Time mandante precisa fazer 3 gols ou menos.' },
            { rotulo: 'CASA -4.5', texto: 'Time mandante precisa fazer 4 gols ou menos.' },
            { rotulo: 'CASA -5.5', texto: 'Time mandante precisa fazer 5 gols ou menos.' },
            { rotulo: 'CASA -6.5', texto: 'Time mandante precisa fazer 6 gols ou menos.' },
            { rotulo: 'CASA -7.5', texto: 'Time mandante precisa fazer 7 gols ou menos.' },
            { rotulo: 'CASA -8.5', texto: 'Time mandante precisa fazer 8 gols ou menos.' },
            { rotulo: 'CASA -9.5', texto: 'Time mandante precisa fazer 9 gols ou menos.' },
            { rotulo: 'VISITANTE +0.5', texto: 'Time visitante precisa fazer 1 gol.', espaco_antes: true },
            { rotulo: 'VISITANTE +1.5', texto: 'Time visitante precisa fazer 2 gols ou mais.' },
            { rotulo: 'VISITANTE +2.5', texto: 'Time visitante precisa fazer 3 gols ou mais.' },
            { rotulo: 'VISITANTE +3.5', texto: 'Time visitante precisa fazer 4 gols ou mais.' },
            { rotulo: 'VISITANTE +4.5', texto: 'Time visitante precisa fazer 5 gols ou mais.' },
            { rotulo: 'VISITANTE +5.5', texto: 'Time visitante precisa fazer 6 gols ou mais.' },
            { rotulo: 'VISITANTE +6.5', texto: 'Time visitante precisa fazer 7 gols ou mais.' },
            { rotulo: 'VISITANTE +7.5', texto: 'Time visitante precisa fazer 8 gols ou mais.' },
            { rotulo: 'VISITANTE +8.5', texto: 'Time visitante precisa fazer 9 gols ou mais.' },
            { rotulo: 'VISITANTE +9.5', texto: 'Time visitante precisa fazer 10 gols ou mais.' },
            { rotulo: 'VISITANTE -0.5', texto: 'Time visitante não marca gol.', espaco_antes: true },
            { rotulo: 'VISITANTE -1.5', texto: 'Time visitante vence e precisa fazer 1 gols ou menos.' },
            { rotulo: 'VISITANTE -2.5', texto: 'Time visitante vence e precisa fazer 2 gols ou menos.' },
            { rotulo: 'VISITANTE -3.5', texto: 'Time visitante vence e precisa fazer 3 gols ou menos.' },
            { rotulo: 'VISITANTE -4.5', texto: 'Time visitante vence e precisa fazer 4 gols ou menos.' },
            { rotulo: 'VISITANTE -5.5', texto: 'Time visitante vence e precisa fazer 5 gols ou menos.' },
            { rotulo: 'VISITANTE -6.5', texto: 'Time visitante vence e precisa fazer 6 gols ou menos.' },
            { rotulo: 'VISITANTE -7.5', texto: 'Time visitante vence e precisa fazer 7 gols ou menos.' },
            { rotulo: 'VISITANTE -8.5', texto: 'Time visitante vence e precisa fazer 8 gols ou menos.' },
            { rotulo: 'VISITANTE -9.5', texto: 'Time visitante vence e precisa fazer 9 gols ou menos.' },
        ],
    },
];
